 version: '2'
 services:
   db:
     image: mysql
     environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students
      MYSQL_USER: django
      MYSQL_PASSWORD: django
   web:
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
