# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('pin', models.IntegerField()),
                ('class_name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='code')),
                ('timestamp', models.DateTimeField(editable=False)),
                ('next', models.TextField(blank=True, editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='code_to_login', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
