# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pin', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField()),
                ('class_name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
