# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileReg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
