# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileReg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
